name: Deploy to Preview Channel

on:
  pull_request:
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: NPM Target
        # You may pin to the exact commit or the version.
        # uses: anna-money/github-actions-npm@c39d5137ed17f1e97cc1fa24019708bd8c89fdb2
        uses: anna-money/github-actions-npm@v2
        with:
          target: build
      
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAGNETAR_80484 }}"
          projectId: magnetar-80484
